### PR TITLE
Feat: OpenMEV v2

### PR DESCRIPTION
**Pull request by aldoborrero**

### CODE REVIEW

**Comment by sambacha** [comment]
#### 📝 Changed routes:


| [**…nge/swap/\[\[...tokens\]\]**](https://sushiswap-interface-96bfnb0hz-manifold.vercel.app/exchange/swap/[[...tokens]]) |
|:-:|
|<a href="https://sushiswap-interface-96bfnb0hz-manifold.vercel.app/exchange/swap/[[...tokens]]">Screenshot of /exchange/swap/[[...tokens]]</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/j0gosqRk3ac0kPw8mb6DJMqzi1lZvdfiIJbZR4wHSTH1hqeauX4RkGjP2Xtn6Xx7-xJi_UIWDaSnbHeuNdPhsw.png">(view full size)</a> |







Commit acc5d598bf37b1d4f9abf698269a36fa3483968e (https://sushiswap-interface-96bfnb0hz-manifold.vercel.app).

**Comment by JamesHayton** [comment]
Is there no way to implement this without the nasty Metamask warning?   As a regular Metamask user, I can say that this defintely feels different than normal Metamask usage?

This is the signing message I get when I test it out: https://imgur.com/a/3SrLh87

And this is with OpenMEV toggled off: https://imgur.com/a/RXu2qTE

I just think that Metamask warning is going to scare most people and I wonder if there are any other options for implementation?

**Comment by sambacha** [comment]
> Is there no way to implement this without the nasty Metamask warning? As a regular Metamask user, I can say that this defintely feels different than normal Metamask usage.
> 
> This is the signing message I get when I test it out: [imgur.com/a/3SrLh87](https://imgur.com/a/3SrLh87)
> 
> And this is with OpenMEV toggled off: [imgur.com/a/RXu2qTE](https://imgur.com/a/RXu2qTE)
> 
> I just think that Metamask warning is going to scare most people and I wonder if there are any other options for implementation?

The alternative is to use our ablative provider, which is not production ready yet. We are working on providing a separate modal window to provide transparency, here is a prototype working example, please give us feedback!

**Comment by JamesHayton** [comment]
This would be a significant improvement.   The more transparency the better.   Would this by styled the same as the Sushiswap interface and appear after the swap button is pressed but before confirm in metamask?   Maybe that existing modal that says waiting for confirmation can be utilized and changed to include the relevant information here so there are still only two modal windows open at the same time?   Just ideas I am tossing out. 

While I am at it, not sure if this is technically possible, but can you detect what RPC a user has set in Metamask at the time they submit the trade?   If so, maybe it's possible to do the following:   1) Say, hey user, looks like you want to use OpenMEV, but to do this we gotta set your RPC to sushirelay...   (don't worry you can change this back later at any time) 2) If they Click yes, then it sets their RPC to sushireplay in metamask (which would then benefit the trader on all Dex's right?)  3)  if they click no, don't do that, the use OpenMEV gas refunder is toggled off?   In this way, the user would then proceed to use metamask as they normally would and for anyone that clicks yes their RPC would be set for future use and benefit without needing anything additional to pop up?  Again, just ideas... but if the metamask RPC can be detected on the sushi side after the user has connected their wallet, I think this may be the best option.

**Review by sambacha — APPROVED** [review]

**Pull request closed without merging**
